### ISSUE TITLE
Why Checking Username Again

### ISSUE THREAD

**Issue by AliAlhajji** [ccaglak/twr#4]
Hello there,
I'm a new Gopher, and I found your project when I was searching for something to learn from.
I came across this line of code when I was reviewing what you did. My understanding is this: you're getting the user from the database using the same username given by r.ParseForm(), creating a new instance 'user' that has the same username. If so, username and user.Username will always be the same, you don't have to check it. Verifying the existence of the username right after getting it from the form would be enough.  

https://github.com/ccaglak/twr/blob/c7871d86aa884db7d41fb5f91ba5df3f3cb27f17/login.go#L30

**Comment by ccaglak** [comment]
Hi Ali, i am learning golang as well however in case it is pointless.
